version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./database/mongo/migrations/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    restart: always
    build:
      context: "./"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
